server:
#服务器端口号配置
  port: 8080
#  ssl:
#    key-store: classpath:www.hnxchmj.cn.pfx
#    key-store-password: MiE46L78
#    key-store-type: PKCS12

spring:
#数据库配置
  datasource:
    url: jdbc:mysql://localhost:3307/bsen_door_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  mvc:
    # D:\MultipartFile
    web.upload-path: /home/hmj/java/bsen
    static-path-pattern: /**
  resources:
    static-locations: classpath\:/META-INF/resources/,classpath\:/resources/,classpath\:/static/,classpath\:/public/,file\:${web.upload-path},classpath\:/static/,classpath:/public/,file:${web.upload-path}
  redis:
      # redis数据库索引（默认为0），我们使用索引为3的数据库，避免和其他数据库冲突
      database: 3
      # redis服务器地址（默认为localhost）
      host: localhost
      # redis端口（默认为6379）
      port: 6379
      # redis访问密码（默认为空）
      password: hmj1991
      # redis连接超时时间（单位为毫秒）
      timeout: 300
      # redis连接池配置
      pool:
        # 最大可用连接数（默认为8，负数表示无限）
        max-active: 8
        # 最大空闲连接数（默认为8，负数表示无限）
        max-idle: 8
        # 最小空闲连接数（默认为0，该值只有为正数才有作用）
        min-idle: 0
        # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
        max-wait: -1
logging:
#sql打印
  level:
   com.nbcb.myron.bsen.dao: debug
mybatis:
  type-aliases-package: com.nbcb.myron.bsen.dao
  mapper-locations: com/nbcb/myron/bsen/dao/BsenDao.xml



